name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore src/Fiap.CustomerService.sln

      - name: Build da aplicação
        run: dotnet build src/Fiap.CustomerService.sln--configuration Release
        
  Tests:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore src/Fiap.CustomerService.Unit.Tests/Fiap.CustomerService.Unit.Tests.csproj

      - name: Executar testes com cobertura
        run: dotnet test src/Fiap.CustomerService.Unit.Tests/Fiap.CustomerService.Unit.Tests.csproj --configuration Release --no-restore
