name: CI/CD - Build, Test and Deploy with AWS SAM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Fiap.CustomerService.sln

      - name: Build
        run: dotnet build src/Fiap.CustomerService.sln --configuration Release --no-restore

      - name: Publish artifacts
        run: dotnet publish src/Fiap.CustomerService.sln  -c Release -o ./publish
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: ./publish

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build src/Fiap.CustomerService.sln --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test src/Fiap.CustomerService.Unit.Tests/Fiap.CustomerService.Unit.Tests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.xml'
